name: Deploy Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      CLOUD_PROVIDER:
        description: Cloud Provider
        required: true
        type: choice
        options:
        - azure
        - aws

      ENVIRONMENT:
        description: Environment
        required: false
        type: choice
        default: dev
        options:
        - dev
        - prod

env:
  TF_VERSION: '1.9.8'

jobs:
  deploy:
    uses: robot-shop/robot-shop-github-actions/.github/workflows/terraform.yaml@main
    with:
      CLOUD_PROVIDER: ${{ github.inputs.CLOUD_PROVIDER }}
      ENVIRONMENT: ${{ github.inputs.ENVIRONMENT }}
      DEPLOY: true