name: Plan Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      CLOUD_PROVIDER:
        description: Cloud Provider
        required: true
        type: choice
        options:
        - azure
        - aws

      ENVIRONMENT:
        description: Environment
        required: false
        type: choice
        default: dev
        options:
        - dev
        - prod

      FORCE_UNLOCK:
        description: "Force unlock state?"
        required: false
        type: string

      UPDATE_LOCK_FILE:
        description: "Update Terraform lock file?"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/terraform.yaml@main
    with:
      CLOUD_PROVIDER: ${{ github.event.inputs.CLOUD_PROVIDER }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      UPDATE_LOCK_FILE: ${{ github.event.inputs.UPDATE_LOCK_FILE }}
      FORCE_UNLOCK: ${{ github.event.inputs.FORCE_UNLOCK }}
      DEPLOY: ${{ github.ref_name == 'main'}}
    secrets: inherit